language: haskell

ghc:
  - 7.8.3
  - 7.6.3
  - 7.4.2

install:
  - cabal install cabal-install
  - cabal install happy
  - cabal install --only-dependencies

script:
  - cabal configure
  - cabal build
  - cabal install

matrix:
  fast_finish: true
  allow_failures:
    - ghc: 7.4.2
    - ghc: 7.6.3

branches:
  only:
    - master

notifications:
  email: false
