language: haskell

ghc:
  - 7.8.4
  - 7.6.3
  - 7.4.2

install:
  - cabal install cabal-install
  - cabal install happy

  # We need to manually fetch and install yeast, as it's not on Hackage
  # yet.
  - git clone https://github.com/stevana/yeast.git
  - cd yeast
  - cabal install
  - cd ..

  - cabal install --only-dependencies

script:
  - cabal configure
  - cabal build
  - cabal install

matrix:
  fast_finish: true
  allow_failures:
    - ghc: 7.4.2
    - ghc: 7.6.3

branches:
  only:
    - master

notifications:
  email: false
